[package]
authors.workspace = true
edition.workspace = true
name = "near-rosetta-rpc"
publish = false
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors.workspace = true
actix-http.workspace = true
actix-web.workspace = true
actix.workspace = true
awc.workspace = true
derive_more.workspace = true
futures.workspace = true
hex.workspace = true
paperclip.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
validator.workspace = true

near-account-id = {path = "../../core/account-id"}
near-chain-configs = {path = "../../core/chain-configs"}
near-client = {path = "../client"}
near-client-primitives = {path = "../client-primitives"}
near-crypto = {path = "../../core/crypto"}
near-network = {path = "../network"}
near-o11y = {path = "../../core/o11y"}
near-primitives = {path = "../../core/primitives"}
node-runtime = {path = "../../runtime/runtime"}

[dev-dependencies]
insta = "1"
near-actix-test-utils = {path = "../../test-utils/actix-test-utils"}

[features]
nightly = []
